[tools]
go = "1.25.5"
gofumpt = "latest"
golangci-lint = "2.8.0"
gotestsum = "latest"
prettier = "latest"

[tasks.build]
alias = ["b"]
description = "Build the Go project"
outputs = ["bin/ado"]
sources = ["*.go", "internal/**/*.*"]
# TODO (tai): rename the output binary
run = "go build -o bin/ado ."

[tasks.run]
alias = ["r"]
depends = ["build"]
run = "bin/ado"

[tasks.lint]
alias = ["l"]
run = "golangci-lint run --fix ./..."

[tasks.test]
alias = ["t"]
run = """
gotestsum --format-hide-empty-pkg --format testdox -- \
   -v -cover -race -timeout=20s ./...
"""
