[tools]
go = "1.25.5"
gofumpt = "latest"
golangci-lint = "2.8.0"
gotestsum = "latest"
lefthook = "1.11.14"
prettier = "latest"

[tasks.build]
alias = ["b"]
description = "Build the Go project"
outputs = ["bin/ado"]
sources = ["*.go", "internal/**/*.*"]
run = [
  "go build -o bin/ado .",
  "ls -lah ./bin/ado",
]

[tasks.run]
alias = ["r"]
depends = ["build"]
run = "bin/ado"

[tasks.lint]
alias = ["l"]
run = "golangci-lint run --fix ./..."

[tasks.test]
alias = ["t"]
run = """
gotestsum --format-hide-empty-pkg --format testdox -- \
   -v -cover -race -timeout=20s ./...
"""

[tasks."fmt:go"]
run = "golangci-lint fmt"

[tasks.release]
alias = ["rel"]
description = "Build the binary with compact size and better performance for release"
outputs = ["bin/ado"]
sources = ["*.go", "internal/**/*.*"]
run = [
  "CGO_ENABLED=0 go build -ldflags=\"-s -w\" -gcflags=\"all=-l -B\" -trimpath -o bin/ado .",
  "ls -lah ./bin/ado",
]
