# $schema: https://mise.jdx.dev/schema/mise-task.json
[tools]
go = "1.25.6"
gofumpt = "latest"
golangci-lint = "2.8.0"
gotestsum = "latest"
lefthook = "2.0.15"
prettier = "latest"

[env]
CGO_ENABLED = "0"
ADO_EXE = "bin/ado" # allow overriding to bin/ado.exe on Windows
_.file = ".env"

[tasks.gen]
description = "Generate code (must be run with native architecture)"
outputs = ["./etc/schemas", "./internal/commands/config_cmd/init.ado.yml"]
sources = ["*.go", "internal/**/*.{go,tpl,md}" ]
run = "go generate ./..."

[tasks.build]
alias = ["b"]
description = "Build the Go project"
depends = ["gen"]
outputs = ["{{env.ADO_EXE}}"]
sources = ["*.go", "internal/**/*.*"]
run = "go build -v -o {{env.ADO_EXE}} ."

[tasks.run]
alias = ["r"]
depends = ["build"]
run = "{{env.ADO_EXE}}"

[tasks.lint]
alias = ["l"]
run = "golangci-lint run --fix ./..."

[tasks.test]
alias = ["t"]
env = { CGO_ENABLED = "1" }
run = "gotestsum --format-hide-empty-pkg --format pkgname -- -v -p 12 -cover -race -timeout=20s ./..."
# can't use race detector on Windows without installing mingw toolchain.
# https://go.dev/doc/articles/race_detector#Requirements
run_windows = "gotestsum --format-hide-empty-pkg --format pkgname -- -v -p 12 -cover -timeout=20s ./..."

[tasks."fmt:go"]
run = "golangci-lint fmt"

[tasks.release]
description = "Build the binary with compact size and better performance for release"
depends = ["gen"]
env = { GOFLAGS = "-ldflags=-s -ldflags=-w -trimpath" }
run = "go build -v -o {{env.ADO_EXE}} ."
