package styles

// ThemeNoTTy only use ascii chars, no color, based on ASCIIStyleConfig from
// https://raw.githubusercontent.com/charmbracelet/glamour/refs/heads/master/styles/styles.go
var ThemeNoTTy = Theme{
	Name:      "noTTY",
	TrueColor: false,
	Tokens: Tokens{
		Text:           "",
		Heading:        "",
		H1:             "",
		H1Background:   "",
		HorizontalRule: "",
		Link:           "",
		LinkText:       "",
		Image:          "",
		ImageText:      "",
		Code:           "",
		CodeBackground: "",
		CodeBlock:      "",
		Chroma: ChromaTokens{
			Text:                "",
			Error:               "",
			ErrorBackground:     "",
			Comment:             "",
			CommentPreproc:      "",
			Keyword:             "",
			KeywordReserved:     "",
			KeywordNamespace:    "",
			KeywordType:         "",
			Operator:            "",
			Punctuation:         "",
			Name:                "",
			NameBuiltin:         "",
			NameTag:             "",
			NameAttribute:       "",
			NameClass:           "",
			NameConstant:        "",
			NameDecorator:       "",
			Function:            "",
			String:              "",
			LiteralStringEscape: "",
			Number:              "",
			GenericDeleted:      "",
			GenericInserted:     "",
			GenericSubheading:   "",
			Background:          "",
		},
	},
}
