package styles

// Light is based on LightStyleConfig from
// https://raw.githubusercontent.com/charmbracelet/glamour/refs/heads/master/styles/styles.go
var Light = Theme{
	Name:      "light",
	TrueColor: true,
	Tokens: Tokens{
		Text:           "234",
		Heading:        "27",
		H1:             "228",
		H1Background:   "63",
		HorizontalRule: "249",
		Link:           "36",
		LinkText:       "29",
		Image:          "205",
		ImageText:      "243",
		Code:           "203",
		CodeBackground: "254",
		CodeBlock:      "242",
		Chroma: ChromaTokens{
			Text:                "#2A2A2A",
			Error:               "#F1F1F1",
			ErrorBackground:     "#FF5555",
			Comment:             "#8D8D8D",
			CommentPreproc:      "#FF875F",
			Keyword:             "#279EFC",
			KeywordReserved:     "#FF5FD2",
			KeywordNamespace:    "#FB406F",
			KeywordType:         "#7049C2",
			Operator:            "#FF2626",
			Punctuation:         "#FA7878",
			Name:                "#212121",
			NameBuiltin:         "#0A1BB1",
			NameTag:             "#581290",
			NameAttribute:       "#8362CB",
			NameClass:           "#212121",
			NameConstant:        "#581290",
			NameDecorator:       "#A3A322",
			Function:            "#019F57",
			String:              "#7E5B38",
			LiteralStringEscape: "#00AEAE",
			Number:              "#22CCAE",
			GenericDeleted:      "#FD5B5B",
			GenericInserted:     "#00D787",
			GenericSubheading:   "#777777",
			Background:          "#373737",
		},
	},
}
