package styles

// TokyoNight is based on
// https://raw.githubusercontent.com/charmbracelet/glamour/refs/heads/master/styles/tokyo-night.go
var TokyoNight = Theme{
	Name:      "tokyo-night",
	TrueColor: true,
	Tokens: Tokens{
		Warn:    "#e0af68",
		Error:   "#f7768e",
		Success: "#9ece6a",
		Markdown: MarkdownTokens{
			Text:           "#a9b1d6",
			Heading:        "#bb9af7",
			H1:             "#2ac3de",
			H1Background:   "",
			HorizontalRule: "#565f89",
			Link:           "#7aa2f7",
			LinkText:       "#2ac3de",
			Image:          "#7aa2f7",
			ImageText:      "#2ac3de",
			Code:           "#9ece6a",
			CodeBackground: "",
			CodeBlock:      "#ff9e64",
		},
		Chroma: ChromaTokens{
			Text:                "#a9b1d6",
			Error:               "#a9b1d6",
			ErrorBackground:     "#f7768e",
			Comment:             "#565f89",
			CommentPreproc:      "#2ac3de",
			Keyword:             "#2ac3de",
			KeywordReserved:     "#2ac3de",
			KeywordNamespace:    "#2ac3de",
			KeywordType:         "#7aa2f7",
			Operator:            "#2ac3de",
			Punctuation:         "#a9b1d6",
			Name:                "#7aa2f7",
			NameBuiltin:         "#7aa2f7",
			NameTag:             "#2ac3de",
			NameAttribute:       "#9ece6a",
			NameClass:           "#7aa2f7",
			NameConstant:        "#bb9af7",
			NameDecorator:       "#9ece6a",
			Function:            "#9ece6a",
			String:              "#e0af68",
			LiteralStringEscape: "#2ac3de",
			Number:              "",
			GenericDeleted:      "#f7768e",
			GenericInserted:     "#9ece6a",
			GenericSubheading:   "#bb9af7",
			Background:          "#1a1b26",
		},
	},
}
