package styles

// Dark is based on DarkStyleConfig from
// https://raw.githubusercontent.com/charmbracelet/glamour/refs/heads/master/styles/styles.go
var Dark = Theme{
	Name:      "dark",
	TrueColor: true,
	Tokens: Tokens{
		Markdown: MarkdownTokens{
			Text:           "252",
			Heading:        "39",
			H1:             "228",
			H1Background:   "63",
			HorizontalRule: "240",
			Link:           "30",
			LinkText:       "35",
			Image:          "212",
			ImageText:      "243",
			Code:           "167",
			CodeBackground: "236",
			CodeBlock:      "244",
		},
		Chroma: ChromaTokens{
			Text:                "#C4C4C4",
			Error:               "#F1F1F1",
			ErrorBackground:     "#F05B5B",
			Comment:             "#676767",
			CommentPreproc:      "#FF875F",
			Keyword:             "#00AAFF",
			KeywordReserved:     "#FF5FD2",
			KeywordNamespace:    "#FF5F87",
			KeywordType:         "#6E6ED8",
			Operator:            "#EF8080",
			Punctuation:         "#E8E8A8",
			Name:                "#C4C4C4",
			NameBuiltin:         "#FF8EC7",
			NameTag:             "#B083EA",
			NameAttribute:       "#7A7AE6",
			NameClass:           "#F1F1F1",
			NameDecorator:       "#FFFF87",
			Function:            "#00D787",
			String:              "#C69669",
			LiteralStringEscape: "#AFFFD7",
			Number:              "#6EEFC0",
			GenericDeleted:      "#FD5B5B",
			GenericInserted:     "#00D787",
			GenericSubheading:   "#777777",
			Background:          "#373737",
		},
	},
}
